# Generated by Django 5.0.3 on 2024-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(max_length=255, verbose_name="Mahsulot turi"),
                ),
                ("volume", models.FloatField(verbose_name="Mahsulot hajmi")),
                (
                    "description",
                    models.TextField(verbose_name="Mahsulot haqida ma'lumot"),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
            },
        ),
    ]
